# Generated by Django 4.2.3 on 2023-07-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
