# Generated by Django 4.2.3 on 2023-07-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_new_category_advert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='numReviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
