# Generated by Django 4.2.3 on 2023-08-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_product_brand_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='images/')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('played', models.IntegerField(blank=True, default=0, null=True)),
                ('won', models.IntegerField(blank=True, default=0, null=True)),
                ('drawn', models.IntegerField(blank=True, default=0, null=True)),
                ('lost', models.IntegerField(blank=True, default=0, null=True)),
                ('goals_for', models.IntegerField(blank=True, default=0, null=True)),
                ('goals_against', models.IntegerField(blank=True, default=0, null=True)),
                ('goal_difference', models.IntegerField(blank=True, default=0, null=True)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_table', to='base.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('team1_score', models.IntegerField(blank=True, default=0, null=True)),
                ('team2_score', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1', to='base.team')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2', to='base.team')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('stadium', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1_fixture', to='base.team')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2_fixture', to='base.team')),
            ],
        ),
    ]
