# Generated by Django 4.2.3 on 2023-08-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_match_stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png', max_length=200, null=True),
        ),
    ]
