# Generated by Django 4.2.3 on 2023-08-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_advert_image_alter_new_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png', max_length=200, null=True),
        ),
    ]
