products = [
  {
    '_id': "1",
    'name': "Oils",
    'image': "/oil.jpeg",
    'description': "High-quality lubricants for various mechanical applications",
   ' brand': "Various Brands",
    'category': "Mechanical Parts",
    'price': 10.99,
    'countInStock': 20,
    'rating': 4.2,
    'numReviews': 15,
  },
  {
    '_id': "2",
    'name': "Pistons",
    'image': "/piston.jpeg",
    'description': "Durable pistons for internal combustion engines",
    'brand': "Various Brands",
    'category': "Mechanical Parts",
    'price': 49.99,
    'countInStock': 8,
    'rating': 4.8,
   ' numReviews': 10,
  },
  {
    '_id': "3",
    'name': "Shock Absorbers",
    'image': "/shock.jpeg",
    'description': "Quality shock absorbers for smooth vehicle suspension",
    'brand': "Various Brands",
    'category': "Mechanical Parts",
    'price': 99.99,
    'countInStock': 15,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': "4",
    'name': "Tires",
    'image': "/tires.jpeg",
    'description': "Durable tires for various vehicles",
    'brand': "Various Brands",
    'category': "Mechanical Parts",
   ' price': 129.99,
    'countInStock': 25,
    'rating': 4.4,
    'numReviews': 20,
  },

  {
    '_id': "5",
    'name': "Headlamp",
    'image': "/headlmps.jpg",
   ' description': "High-quality alternators for various vehicles",
    'brand': "Various Brands",
    'category': "Mechanical Parts",
    'price': 149.99,
    'countInStock': 10,
    'rating': 4.7,
    'numReviews': 18,
  },
  {
    '_id': "6",
    'name': "Battery",
    'image': "/battery.jpg",
    'description': "High-quality batteries for various vehicles",
    'brand': "Various Brands",
    'category': "Mechanical Parts",
    'price': 99.99,
    'countInStock': 0,
    'rating': 4.9,
    'numReviews': 20,
  },
];


